site_name: Base de Conhecimentos da Plataforma
site_url: https://172.19.4.153:8000
theme:
  name: material
  palette:
    primary: custom
  language: pt-BR
  logo:
    assets/logo_branca.png
  features:
    - navigation.path
    - navigation.top
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/bridge-brand.js?v=13
  
extra:
  generator: false   # üîπ remove a barra "Made with Material for MkDocs"
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Vis√£o Geral:
    - Vis√£o Geral: 1.Vis√£o_Geral__brand-target.md
    - Vis√£o Geral: 1.Vis√£o_Geral__brand-serpro.md
    - Vis√£o Geral: 1.Vis√£o_Geral__brand-whitelabel.md
    - Vis√£o Geral: 1.Vis√£o_Geral__brand-planejar.md
    - Um pouco de hist√≥ria: 1.1_Um_pouco_de_hist√≥ria__brand-planejar.md
    - Um pouco de hist√≥ria: 1.1_Um_pouco_de_hist√≥ria__brand-serpro.md
    - Um pouco de hist√≥ria: 1.1_Um_pouco_de_hist√≥ria__brand-target.md
    - Um pouco de hist√≥ria: 1.1_Um_pouco_de_hist√≥ria__brand-whitelabel.md
    - A Plataforma: 1.2_A_Plataforma__brand-planejar.md
    - A Plataforma: 1.2_A_Plataforma__brand-serpro.md
    - A Plataforma: 1.2_A_Plataforma__brand-target.md
    - A Plataforma: 1.2_A_Plataforma__brand-whitelabel.md
    - Estrutura da Plataforma: 1.3_Estrutura_da_Plataforma.md
    - Reuni√µes de Monitoramento: 1.4_Reuni√µes_de_Monitoramento.md
    - Estrutura de atualiza√ß√£o e inclus√£o das informa√ß√µes: 1.5_Estrutura_de_atualiza√ß√£o_e_inclus√£o_das_informa√ß√µes.md
    - Gloss√°rio: 1.6_Gloss√°rio.md
    - Barra de Navega√ß√£o: 1.7_Conhecendo_a_barra_de_navega√ß√£o.md
    - Central de Notifica√ß√µes: 1.8_Central_de_notifica√ß√µes.md
    - Minha P√°gina: 1.9_Minha_p√°gina.md
  - N√≠veis de Informa√ß√£o:
    - N√≠veis de Informa√ß√£o: 2_N√≠veis_de_Informa√ß√£o.md
    - Cria√ß√£o dos N√≠veis (N1, N2, N3, N4, N5 e N6): 2.1_Cria√ß√£o_dos_N√≠veis_(N1,_N2,_N3,_N4,_N5_e_N6).md
    - Como Editar e Remover Entidades: 2.2_Como_Editar_e_Remover_Entidades.md
    - P√°gina da Entidade: 3.1_P√°gina_da_Entidade.md
    - Bloco Detalhado: 3.20_Bloco_Detalhado.md
    - Canvas: 3.21_Canvas.md
    - Quadro de Vis√µes: 3.22_Quadro_de_Vis√µes.md
    - Menu de A√ß√µes:
      - Menu de A√ß√µes: 3.2_Menu_de_A√ß√µes.md
      - Mover, Copiar Entidades: 3.2.1_Mover,_Copiar_Entidades.md
      - Observa√ß√µes, Notas T√©cnicas: 3.2.2_Observa√ß√µes,_Notas_T√©cnicas.md
      - Entidades Vinculadas: 3.2.3_Entidades_Vinculadas.md
      - Galeria de Imagens: 3.2.4_Galeria_de_Imagens.md
      - Problemas: 3.4.6_Problemas.md
    - Envolvidos nos Projetos:
      - Envolvidos nos Projetos: 3.3_Envolvidos_nos_Projetos.md
      - √öltimas atualiza√ß√µes: 3.4_√öltimas_atualiza√ß√µes.md
      - Reposit√≥rio de Documentos: 3.4.5_Reposit√≥rio_de_Documentos.md
      - Riscos: 3.4.7_Riscos.md
    - Modelos de Entidades:
      - Modelos de Entidades: 3.5_Modelos_de_Entidades.md
      - Criar entidade baseada em template: 3.5.1_Criar_entidade_baseada_em_template.md
      - Gerenciador de Templates: 3.5.2_Gerenciador_de_Templates.md
    - Configura√ß√µes de Datas: 3.6_Configura√ß√µes_de_Datas.md
    - Checklist: 3.7_Checklist.md
    - Importa√ß√£o de entidades: 3.8_Importa√ß√£o_de_entidades.md
    - Planilhas: 3.9_Planilhas.md
    - Financeiro: 3.10_Financeiro.md
    - Imagem mapeada: 3.11_Imagem_mapeada.md
    - Gantt Sincronizado: 3.12_Gantt_Sincronizado.md
    - Criando Projetos no Gantt: 3.12.1_Criando_Projetos_no_Gantt.md
    - Importando Arquivos do Project: 3.12.2_Importando_Arquivos_do_Project.md
    - Quadro de Projetos - Kanban: 3.13_Quadro_de_Projetos_Kanban.md
    - Quadro Estrat√©gico: 3.14_Quadro_Estrat√©gico.md
    - Vers√°til: 3.15_Vers√°til.md
    - Bloco Agrupado: 3.16_Bloco_Agrupado.md
    - Linha de Base: 3.17_Linha_de_base.md
    - Gr√°fico de evolu√ß√£o do Projeto: 3.18_Gr√°fico_de_evolu√ß√£o_do_Projeto.md
  - Gest√£o de Indicadores:
      - Gest√£o de Indicadores: 5_Gest√£o_de_Indicadores.md
      - Gerenciador de Indicadores: 5.1_Gerenciador_de_Indicadores.md
      - Matriz de Indicadores: 5.2_Matriz_de_Indicadores.md
      - Indicadores Compostos: 5.4_Indicadores_Compostos.md
      - An√°lise de Desempenho do Indicador: 5.5_An√°lise_de_Desempenho_do_Indicador.md
      - M√©todo de c√°lculo e polaridade: 5.7_M√©todo_de_c√°lculo_e_polaridade.md
      - Indicadores Simples: 5.8_Indicadores_Simples.md
      - Vincular Indicadores √†s Entidades: 5.9_Vincular_Indicadores_√†s_Entidades.md
      - Editar Indicadores em Massa: 5.10_Editar_indicadores_em_massa.md
  - Campos Din√¢micos:
    - Campos Din√¢micos: 3.19_Campos_Din√¢micos.md
    - Publicador de Campos Din√¢mico: 3.19.1_Publicador_de_Campos_Din√¢mico.md
  - Reuni√µes, Apresenta√ß√µes e Encaminhamentos:
    - Reuni√µes, Apresenta√ß√µes e Encaminhamentos: 6_Reuni√µes,_Apresenta√ß√µes_e_Encaminhamentos.md
    - Apresenta√ß√µes: 6.1_Apresenta√ß√µes.md
    - Atas de Reuni√£o: 6.2_Atas_de_Reuni√£o.md
    - Confirma√ß√£o de participa√ß√£o na reuni√£o com Justificativa: 6.2.2_Confirma√ß√£o_de_participa√ß√£o_na_reuni√£o_com_Justificativa.md
    - Vincular Encaminhamentos na Ata de Reuni√£o: 6.2.3_Vincular_Encaminhamentos_na_Ata_de_Reuni√£o.md
    - Relat√≥rio de Participantes da Reuni√£o: 6.2.4_Relat√≥rio_de_Participantes_da_Reuni√£o.md
    - Encaminhamentos: 6.3_Encaminhamentos.md
    - Gerenciador de Encaminhamentos: 6.3.2_Gerenciador_de_Encaminhamentos.md
    - Quadro Kanban de Encaminhamentos: 6.3.3_Quadro_Kanban_de_Encaminhamentos.md
  - Relat√≥rios e Dashboards:
    - Relat√≥rios e Dashboards: 7_Relat√≥rios_e_Dashboards.md
    - Exporta√ß√£o de Entidades: 7.1_Exporta√ß√£o_de_Entidades.md
  - Relat√≥rios Gerenciais:
    - Relat√≥rios Gerenciais: 7.2_Relat√≥rios_Gerenciais.md
    - Relat√≥rio Situacional Detalhado: 7.2.1_Relat√≥rio_Situacional_Detalhado.md
    - Relat√≥rio de Log de Permiss√µes de Usu√°rios Geradas a partir dos Grupos para Gestores: 7.2.2_Relat√≥rio_de_Log_de_Permiss√µes_de_Usu√°rios_Geradas_a_partir_dos_Grupos_para_Gestores.md
    - Exporta√ß√£o de Indicadores: 7.3_Exporta√ß√£o_de_Indicadores.md
    - Dashboard ODS: 7.8_Dashboard_ODS.md
    - Gest√£o da Comunica√ß√£o: 8_Gest√£o_da_Comunica√ß√£o.md
    - Exportar Encaminhamentos: 7.9_Exporta√ßao_de_encaminhamentos.md
  - Geolocaliza√ß√£o:
    - Geolocaliza√ß√£o: 9_Geolocaliza√ß√£o.md
    - Localiza√ß√£o Geogr√°fica das Entidades: 9.1_Localiza√ß√£o_Geogr√°fica_das_Entidades.md
    - Mapa da Regionaliza√ß√£o: 9.2_Mapa_da_Regionaliza√ß√£o.md
  - Administra√ß√£o da Plataforma:
    - Administra√ß√£o da Plataforma: 10_Administra√ß√£o_da_Plataforma.md
    - Configura√ß√£o de P√°ginas: 10.1_Configura√ß√£o_de_P√°ginas.md
    - Cria√ß√£o de P√°ginas: 10.1.4_Cria√ß√£o_de_P√°ginas.md
    - Configura√ß√£o de N Abas nas Entidades: 10.1.5_Configura√ß√£o_de_N_Abas_nas_Entidades.md
    - Cadastros Auxiliares: 10.2_Cadastros_Auxiliares.md
    - Cria√ß√£o de Tags: 10.2.1_Cria√ß√£o_de_Tags.md
    - Respons√°veis: 10.2.2_Respons√°veis.md
    - Card de Institui√ß√µes com Preview: 10.2.3.1_Card de Institui√ß√µes com Preview.md
    - Institui√ß√µes (departamentos): 10.2.3_Institui√ß√µes_departamentos.md
    - Fontes e Grupos Financeiros: 10.2.4_Fontes e Grupos Financeiros.md
    - Status / Status Informado: 10.2.5_Status_Status Informado.md
    - Gest√£o de Usu√°rios: 10.3_Gest√£o_de_Usu√°rios.md
    - Grupos de Usu√°rios: 10.4_Grupos_de_Usu√°rios.md
    - Permiss√µes: 10.5_Permiss√µes.md
    - Permiss√µes de Encaminhamentos: 10.5.3_Permiss√µes_de_Encaminhamentos.md
    - Permiss√µes de Indicadores: 10.5.2_Permiss√µes_de_Indicadores.md
    - Adicionar permiss√µes em Lote: 10.5.4_Adicionar_permiss√µes_em_Lote.md
    - Papel Customizado: 10.7_Papel_Customizado.md
    - Permiss√£o de visualizar e atribuir institui√ß√µes: 10.7.1_Permiss√£o_de_visualizar_e_atribuir_institui√ß√µes.md
    - Configura√ß√£o de Funcionalidades: 10.8_Configura√ß√£o_de_Funcionalidades.md
    - Idioma: 10.11_Idioma.md
    - Tema: 10.12_Tema.md
    - Configura√ß√£o de E-mail: 10.13_Configura√ß√£o_de_E-mail.md
    - Modelos de Notifica√ß√µes: 10.14_Modelos_de_Notifica√ß√µes.md
    - Migra√ß√£o de Ano: 10.15_Migra√ß√£o_de_Ano.md
    - Acesso R√°pido: 10.16_Acesso_R√°pido.md
    - Aplicativos Android & IOS: 
    - Pol√≠tica de Privacidade: 11.4_Pol√≠tica_de_Privacidade.md
    - Integra√ß√µes: 12_Integra√ß√µes.md
    - Plataforma x AD (Active Directory): 12.1_Plataforma_x_AD_Active Directory.md
    - Experi√™ncias de Integra√ß√£o realizadas: 12.1.2_Experi√™ncias_de_Integra√ß√£o_realizadas.md
    - Integra√ß√£o com Sistema de Obras: 12.1.3_Integra√ß√£o_com_Sistema_de_Obras.md
  - Metodologias de Gest√£o:
    - Metodologias de Gest√£o: 13_Metodologias_de_Gest√£o.md
    - Projetos: 13.1_Projetos.md
    - Mapa Estrat√©gico: 13.2_Mapa_Estrat√©gico.md
    - BSC- Balanced Score Card: 13.3_BSC_-_Balanced_Score_Card.md
    - Gest√£o a Vista: 13.4_Gest√£o_a_Vista.md
    - KPI- Key Performance Indicator: 13.5_KPI_-_Key_Performance_Indicator.md
    - OKR- Objectives and Key Results: 13.6_OKR_-_Objectives_and_Key_Results.md
    - Canvas: 13.7_Canvas.md
    - Scrum: 13.8_Scrum.md
    - 5W2H: 13.9_5W2H.md
    - 5 WHY'S: 13.10_5_WHY'S.md
    - Mapa Mental: 13.11_Mapa_Mental.md
    - Kanban: 13.12_Kanban.md
  - App Android e IOs: 16_Plataforma_App.md  
  - Hist√≥rias de Sucesso:
    - Hist√≥rias de Sucesso: 15_Como_a_Plataforma_Est√°_Transformando_a_Gest√£o_de_Projetos.md
    - Monitora Bahia: 15.1_Monitora_Bahia.md
    - Depoimento sobre o Monitora Bahia: 15.2_Depoimento_sobre_o_Monitora_Bahia.md
    - Saiu na Globo: 15.3_Saiu_na_Globo.md
